const CONSTANTS = {
  SET_TEXT: "SET_TEXT",
  TOGGLE_DIRECTION: "TOGGLE_DIRECTION",
  SET_SORTBY: "SET_SORTBY",
  SHOW_MESSAGE: "SHOW_MESSAGE",
  SET_FILTER: "SET_FILTER"
};

export default CONSTANTS;
